dependencies {
	compileOnly group: "com.liferay.portal", name: "release.portal.api"

	// https://mvnrepository.com/artifact/com.liferay/com.liferay.css.builder
	implementation("com.liferay:com.liferay.css.builder:3.1.6")
	// Clay taglib.
	compileOnly group: 'com.liferay', name: 'com.liferay.frontend.taglib.clay'
	// Needed for the Assignments Management Toolbar.
	compileOnly group: 'com.liferay', name: 'com.liferay.petra.function'
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel"
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.taglib"
	compileOnly group: "javax.portlet", name: "portlet-api"
	// compileOnly group: "jakarta.servlet", name: "jakarta.servlet-api", version: "4.0.4"
	// https://mvnrepository.com/artifact/jakarta.servlet/jakarta.servlet-api
	compileOnly("jakarta.servlet:jakarta.servlet-api:4.0.4")

	compileOnly group: "jstl", name: "jstl"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations"
	// Gradebook service.
	compileOnly project(":modules:gradebook:gradebook-api")
}

tasks.withType(JavaCompile) {
// Generated classes using Jodd library are unable to be read when compiled against JDK
sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21
}