/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.petclinic.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.training.petclinic.model.Appointment;
import com.liferay.training.petclinic.model.AppointmentModel;
import com.liferay.training.petclinic.model.AppointmentSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Appointment service. Represents a row in the &quot;PetClinic_Appointment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppointmentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppointmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppointmentImpl
 * @generated
 */
@JSON(strict = true)
public class AppointmentModelImpl
	extends BaseModelImpl<Appointment> implements AppointmentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appointment model instance should use the <code>Appointment</code> interface instead.
	 */
	public static final String TABLE_NAME = "PetClinic_Appointment";

	public static final Object[][] TABLE_COLUMNS = {
		{"appointmentId", Types.BIGINT}, {"petId", Types.BIGINT},
		{"vetId", Types.BIGINT}, {"date_", Types.TIMESTAMP},
		{"description", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("appointmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("petId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("vetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("date_", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PetClinic_Appointment (appointmentId LONG not null primary key,petId LONG,vetId LONG,date_ DATE null,description VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table PetClinic_Appointment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appointment.appointmentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PetClinic_Appointment.appointmentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PETID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VETID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPOINTMENTID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Appointment toModel(AppointmentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Appointment model = new AppointmentImpl();

		model.setAppointmentId(soapModel.getAppointmentId());
		model.setPetId(soapModel.getPetId());
		model.setVetId(soapModel.getVetId());
		model.setDate(soapModel.getDate());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Appointment> toModels(AppointmentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Appointment> models = new ArrayList<Appointment>(
			soapModels.length);

		for (AppointmentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public AppointmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appointmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppointmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appointmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Appointment.class;
	}

	@Override
	public String getModelClassName() {
		return Appointment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Appointment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Appointment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Appointment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Appointment)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Appointment, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Appointment, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Appointment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Appointment, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Appointment, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Appointment, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<Appointment, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Appointment, Object>>();

		attributeGetterFunctions.put(
			"appointmentId", Appointment::getAppointmentId);
		attributeGetterFunctions.put("petId", Appointment::getPetId);
		attributeGetterFunctions.put("vetId", Appointment::getVetId);
		attributeGetterFunctions.put("date", Appointment::getDate);
		attributeGetterFunctions.put(
			"description", Appointment::getDescription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<Appointment, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<Appointment, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Appointment, ?>>();

		attributeSetterBiConsumers.put(
			"appointmentId",
			(BiConsumer<Appointment, Long>)Appointment::setAppointmentId);
		attributeSetterBiConsumers.put(
			"petId", (BiConsumer<Appointment, Long>)Appointment::setPetId);
		attributeSetterBiConsumers.put(
			"vetId", (BiConsumer<Appointment, Long>)Appointment::setVetId);
		attributeSetterBiConsumers.put(
			"date", (BiConsumer<Appointment, Date>)Appointment::setDate);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<Appointment, String>)Appointment::setDescription);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getAppointmentId() {
		return _appointmentId;
	}

	@Override
	public void setAppointmentId(long appointmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appointmentId = appointmentId;
	}

	@JSON
	@Override
	public long getPetId() {
		return _petId;
	}

	@Override
	public void setPetId(long petId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petId = petId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPetId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("petId"));
	}

	@JSON
	@Override
	public long getVetId() {
		return _vetId;
	}

	@Override
	public void setVetId(long vetId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vetId = vetId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalVetId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("vetId"));
	}

	@JSON
	@Override
	public Date getDate() {
		return _date;
	}

	@Override
	public void setDate(Date date) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_date = date;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Appointment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Appointment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Appointment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppointmentImpl appointmentImpl = new AppointmentImpl();

		appointmentImpl.setAppointmentId(getAppointmentId());
		appointmentImpl.setPetId(getPetId());
		appointmentImpl.setVetId(getVetId());
		appointmentImpl.setDate(getDate());
		appointmentImpl.setDescription(getDescription());

		appointmentImpl.resetOriginalValues();

		return appointmentImpl;
	}

	@Override
	public int compareTo(Appointment appointment) {
		long primaryKey = appointment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Appointment)) {
			return false;
		}

		Appointment appointment = (Appointment)object;

		long primaryKey = appointment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Appointment> toCacheModel() {
		AppointmentCacheModel appointmentCacheModel =
			new AppointmentCacheModel();

		appointmentCacheModel.appointmentId = getAppointmentId();

		appointmentCacheModel.petId = getPetId();

		appointmentCacheModel.vetId = getVetId();

		Date date = getDate();

		if (date != null) {
			appointmentCacheModel.date = date.getTime();
		}
		else {
			appointmentCacheModel.date = Long.MIN_VALUE;
		}

		appointmentCacheModel.description = getDescription();

		String description = appointmentCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			appointmentCacheModel.description = null;
		}

		return appointmentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Appointment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Appointment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Appointment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Appointment)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Appointment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Appointment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Appointment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Appointment)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Appointment>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Appointment.class, ModelWrapper.class);

	}

	private long _appointmentId;
	private long _petId;
	private long _vetId;
	private Date _date;
	private String _description;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Appointment, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Appointment)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("appointmentId", _appointmentId);
		_columnOriginalValues.put("petId", _petId);
		_columnOriginalValues.put("vetId", _vetId);
		_columnOriginalValues.put("date_", _date);
		_columnOriginalValues.put("description", _description);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("date_", "date");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("appointmentId", 1L);

		columnBitmasks.put("petId", 2L);

		columnBitmasks.put("vetId", 4L);

		columnBitmasks.put("date_", 8L);

		columnBitmasks.put("description", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Appointment _escapedModel;

}