/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.petclinic.model.impl;

import com.liferay.training.petclinic.model.Appointment;
import com.liferay.training.petclinic.service.AppointmentLocalServiceUtil;

/**
 * The extended model base implementation for the Appointment service. Represents a row in the &quot;PetClinic_Appointment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppointmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppointmentImpl
 * @see Appointment
 * @generated
 */
public abstract class AppointmentBaseImpl
	extends AppointmentModelImpl implements Appointment {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appointment model instance should use the <code>Appointment</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AppointmentLocalServiceUtil.addAppointment(this);
		}
		else {
			AppointmentLocalServiceUtil.updateAppointment(this);
		}
	}

}