/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.petclinic.model.impl;

import com.liferay.training.petclinic.model.Owner;
import com.liferay.training.petclinic.service.OwnerLocalServiceUtil;

/**
 * The extended model base implementation for the Owner service. Represents a row in the &quot;PetClinic_Owner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OwnerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OwnerImpl
 * @see Owner
 * @generated
 */
public abstract class OwnerBaseImpl extends OwnerModelImpl implements Owner {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a owner model instance should use the <code>Owner</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			OwnerLocalServiceUtil.addOwner(this);
		}
		else {
			OwnerLocalServiceUtil.updateOwner(this);
		}
	}

}