/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.petclinic.model.impl;

import com.liferay.training.petclinic.model.Pet;
import com.liferay.training.petclinic.service.PetLocalServiceUtil;

/**
 * The extended model base implementation for the Pet service. Represents a row in the &quot;PetClinic_Pet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PetImpl
 * @see Pet
 * @generated
 */
public abstract class PetBaseImpl extends PetModelImpl implements Pet {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a pet model instance should use the <code>Pet</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PetLocalServiceUtil.addPet(this);
		}
		else {
			PetLocalServiceUtil.updatePet(this);
		}
	}

}