/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.petclinic.model.impl;

import com.liferay.training.petclinic.model.Specialty;
import com.liferay.training.petclinic.service.SpecialtyLocalServiceUtil;

/**
 * The extended model base implementation for the Specialty service. Represents a row in the &quot;PetClinic_Specialty&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SpecialtyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SpecialtyImpl
 * @see Specialty
 * @generated
 */
public abstract class SpecialtyBaseImpl
	extends SpecialtyModelImpl implements Specialty {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a specialty model instance should use the <code>Specialty</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SpecialtyLocalServiceUtil.addSpecialty(this);
		}
		else {
			SpecialtyLocalServiceUtil.updateSpecialty(this);
		}
	}

}