/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.petclinic.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.training.petclinic.model.Vet;
import com.liferay.training.petclinic.model.VetModel;
import com.liferay.training.petclinic.model.VetSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Vet service. Represents a row in the &quot;PetClinic_Vet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VetModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VetImpl
 * @generated
 */
@JSON(strict = true)
public class VetModelImpl extends BaseModelImpl<Vet> implements VetModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vet model instance should use the <code>Vet</code> interface instead.
	 */
	public static final String TABLE_NAME = "PetClinic_Vet";

	public static final Object[][] TABLE_COLUMNS = {
		{"vetId", Types.BIGINT}, {"firstName", Types.VARCHAR},
		{"lastName", Types.VARCHAR}, {"specialties", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("vetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("specialties", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PetClinic_Vet (vetId LONG not null primary key,firstName VARCHAR(75) null,lastName VARCHAR(75) null,specialties VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table PetClinic_Vet";

	public static final String ORDER_BY_JPQL = " ORDER BY vet.vetId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PetClinic_Vet.vetId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VETID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Vet toModel(VetSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Vet model = new VetImpl();

		model.setVetId(soapModel.getVetId());
		model.setFirstName(soapModel.getFirstName());
		model.setLastName(soapModel.getLastName());
		model.setSpecialties(soapModel.getSpecialties());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Vet> toModels(VetSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Vet> models = new ArrayList<Vet>(soapModels.length);

		for (VetSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public VetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _vetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _vetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Vet.class;
	}

	@Override
	public String getModelClassName() {
		return Vet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Vet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Vet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Vet, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Vet)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Vet, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Vet, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Vet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Vet, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Vet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Vet, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<Vet, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Vet, Object>>();

		attributeGetterFunctions.put("vetId", Vet::getVetId);
		attributeGetterFunctions.put("firstName", Vet::getFirstName);
		attributeGetterFunctions.put("lastName", Vet::getLastName);
		attributeGetterFunctions.put("specialties", Vet::getSpecialties);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<Vet, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<Vet, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Vet, ?>>();

		attributeSetterBiConsumers.put(
			"vetId", (BiConsumer<Vet, Long>)Vet::setVetId);
		attributeSetterBiConsumers.put(
			"firstName", (BiConsumer<Vet, String>)Vet::setFirstName);
		attributeSetterBiConsumers.put(
			"lastName", (BiConsumer<Vet, String>)Vet::setLastName);
		attributeSetterBiConsumers.put(
			"specialties", (BiConsumer<Vet, String>)Vet::setSpecialties);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getVetId() {
		return _vetId;
	}

	@Override
	public void setVetId(long vetId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vetId = vetId;
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstName = firstName;
	}

	@JSON
	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastName = lastName;
	}

	@JSON
	@Override
	public String getSpecialties() {
		if (_specialties == null) {
			return "";
		}
		else {
			return _specialties;
		}
	}

	@Override
	public void setSpecialties(String specialties) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_specialties = specialties;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Vet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Vet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Vet> escapedModelProxyProviderFunction =
				EscapedModelProxyProviderFunctionHolder.
					_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VetImpl vetImpl = new VetImpl();

		vetImpl.setVetId(getVetId());
		vetImpl.setFirstName(getFirstName());
		vetImpl.setLastName(getLastName());
		vetImpl.setSpecialties(getSpecialties());

		vetImpl.resetOriginalValues();

		return vetImpl;
	}

	@Override
	public int compareTo(Vet vet) {
		long primaryKey = vet.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Vet)) {
			return false;
		}

		Vet vet = (Vet)object;

		long primaryKey = vet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Vet> toCacheModel() {
		VetCacheModel vetCacheModel = new VetCacheModel();

		vetCacheModel.vetId = getVetId();

		vetCacheModel.firstName = getFirstName();

		String firstName = vetCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			vetCacheModel.firstName = null;
		}

		vetCacheModel.lastName = getLastName();

		String lastName = vetCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			vetCacheModel.lastName = null;
		}

		vetCacheModel.specialties = getSpecialties();

		String specialties = vetCacheModel.specialties;

		if ((specialties != null) && (specialties.length() == 0)) {
			vetCacheModel.specialties = null;
		}

		return vetCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Vet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Vet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Vet, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Vet)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Vet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Vet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Vet, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Vet)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Vet>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Vet.class, ModelWrapper.class);

	}

	private long _vetId;
	private String _firstName;
	private String _lastName;
	private String _specialties;

	public <T> T getColumnValue(String columnName) {
		Function<Vet, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Vet)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("vetId", _vetId);
		_columnOriginalValues.put("firstName", _firstName);
		_columnOriginalValues.put("lastName", _lastName);
		_columnOriginalValues.put("specialties", _specialties);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("vetId", 1L);

		columnBitmasks.put("firstName", 2L);

		columnBitmasks.put("lastName", 4L);

		columnBitmasks.put("specialties", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Vet _escapedModel;

}