/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.petclinic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Appointment service. Represents a row in the &quot;PetClinic_Appointment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.petclinic.model.impl.AppointmentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.petclinic.model.impl.AppointmentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Appointment
 * @generated
 */
@ProviderType
public interface AppointmentModel extends BaseModel<Appointment> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a appointment model instance should use the {@link Appointment} interface instead.
	 */

	/**
	 * Returns the primary key of this appointment.
	 *
	 * @return the primary key of this appointment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this appointment.
	 *
	 * @param primaryKey the primary key of this appointment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the appointment ID of this appointment.
	 *
	 * @return the appointment ID of this appointment
	 */
	public long getAppointmentId();

	/**
	 * Sets the appointment ID of this appointment.
	 *
	 * @param appointmentId the appointment ID of this appointment
	 */
	public void setAppointmentId(long appointmentId);

	/**
	 * Returns the pet ID of this appointment.
	 *
	 * @return the pet ID of this appointment
	 */
	public long getPetId();

	/**
	 * Sets the pet ID of this appointment.
	 *
	 * @param petId the pet ID of this appointment
	 */
	public void setPetId(long petId);

	/**
	 * Returns the vet ID of this appointment.
	 *
	 * @return the vet ID of this appointment
	 */
	public long getVetId();

	/**
	 * Sets the vet ID of this appointment.
	 *
	 * @param vetId the vet ID of this appointment
	 */
	public void setVetId(long vetId);

	/**
	 * Returns the date of this appointment.
	 *
	 * @return the date of this appointment
	 */
	public Date getDate();

	/**
	 * Sets the date of this appointment.
	 *
	 * @param date the date of this appointment
	 */
	public void setDate(Date date);

	/**
	 * Returns the description of this appointment.
	 *
	 * @return the description of this appointment
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this appointment.
	 *
	 * @param description the description of this appointment
	 */
	public void setDescription(String description);

}