/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.petclinic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Owner service. Represents a row in the &quot;PetClinic_Owner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.petclinic.model.impl.OwnerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.petclinic.model.impl.OwnerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Owner
 * @generated
 */
@ProviderType
public interface OwnerModel extends BaseModel<Owner> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a owner model instance should use the {@link Owner} interface instead.
	 */

	/**
	 * Returns the primary key of this owner.
	 *
	 * @return the primary key of this owner
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this owner.
	 *
	 * @param primaryKey the primary key of this owner
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the owner ID of this owner.
	 *
	 * @return the owner ID of this owner
	 */
	public long getOwnerId();

	/**
	 * Sets the owner ID of this owner.
	 *
	 * @param ownerId the owner ID of this owner
	 */
	public void setOwnerId(long ownerId);

	/**
	 * Returns the first name of this owner.
	 *
	 * @return the first name of this owner
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this owner.
	 *
	 * @param firstName the first name of this owner
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this owner.
	 *
	 * @return the last name of this owner
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this owner.
	 *
	 * @param lastName the last name of this owner
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the address of this owner.
	 *
	 * @return the address of this owner
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this owner.
	 *
	 * @param address the address of this owner
	 */
	public void setAddress(String address);

	/**
	 * Returns the city of this owner.
	 *
	 * @return the city of this owner
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this owner.
	 *
	 * @param city the city of this owner
	 */
	public void setCity(String city);

	/**
	 * Returns the telephone of this owner.
	 *
	 * @return the telephone of this owner
	 */
	@AutoEscape
	public String getTelephone();

	/**
	 * Sets the telephone of this owner.
	 *
	 * @param telephone the telephone of this owner
	 */
	public void setTelephone(String telephone);

}