/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.petclinic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Pet service. Represents a row in the &quot;PetClinic_Pet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.petclinic.model.impl.PetModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.petclinic.model.impl.PetImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Pet
 * @generated
 */
@ProviderType
public interface PetModel extends BaseModel<Pet> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pet model instance should use the {@link Pet} interface instead.
	 */

	/**
	 * Returns the primary key of this pet.
	 *
	 * @return the primary key of this pet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pet.
	 *
	 * @param primaryKey the primary key of this pet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the pet ID of this pet.
	 *
	 * @return the pet ID of this pet
	 */
	public long getPetId();

	/**
	 * Sets the pet ID of this pet.
	 *
	 * @param petId the pet ID of this pet
	 */
	public void setPetId(long petId);

	/**
	 * Returns the owner ID of this pet.
	 *
	 * @return the owner ID of this pet
	 */
	public long getOwnerId();

	/**
	 * Sets the owner ID of this pet.
	 *
	 * @param ownerId the owner ID of this pet
	 */
	public void setOwnerId(long ownerId);

	/**
	 * Returns the name of this pet.
	 *
	 * @return the name of this pet
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this pet.
	 *
	 * @param name the name of this pet
	 */
	public void setName(String name);

	/**
	 * Returns the birth date of this pet.
	 *
	 * @return the birth date of this pet
	 */
	public Date getBirthDate();

	/**
	 * Sets the birth date of this pet.
	 *
	 * @param birthDate the birth date of this pet
	 */
	public void setBirthDate(Date birthDate);

	/**
	 * Returns the type of this pet.
	 *
	 * @return the type of this pet
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this pet.
	 *
	 * @param type the type of this pet
	 */
	public void setType(String type);

}