/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.petclinic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Specialty service. Represents a row in the &quot;PetClinic_Specialty&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.petclinic.model.impl.SpecialtyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.petclinic.model.impl.SpecialtyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Specialty
 * @generated
 */
@ProviderType
public interface SpecialtyModel extends BaseModel<Specialty> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a specialty model instance should use the {@link Specialty} interface instead.
	 */

	/**
	 * Returns the primary key of this specialty.
	 *
	 * @return the primary key of this specialty
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this specialty.
	 *
	 * @param primaryKey the primary key of this specialty
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the specialty ID of this specialty.
	 *
	 * @return the specialty ID of this specialty
	 */
	public long getSpecialtyId();

	/**
	 * Sets the specialty ID of this specialty.
	 *
	 * @param specialtyId the specialty ID of this specialty
	 */
	public void setSpecialtyId(long specialtyId);

	/**
	 * Returns the name of this specialty.
	 *
	 * @return the name of this specialty
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this specialty.
	 *
	 * @param name the name of this specialty
	 */
	public void setName(String name);

}